-- phpMyAdmin SQL Dump
-- version 5.0.3
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: May 02, 2021 at 09:13 PM
-- Server version: 10.4.14-MariaDB
-- PHP Version: 7.4.11

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `projektemail`
--

-- --------------------------------------------------------

--
-- Table structure for table `emaile`
--

CREATE TABLE `emaile` (
  `id` int(11) NOT NULL,
  `nadawca` varchar(50) COLLATE utf8mb4_polish_ci NOT NULL,
  `tytul` varchar(50) COLLATE utf8mb4_polish_ci NOT NULL,
  `tresc` text COLLATE utf8mb4_polish_ci NOT NULL,
  `kategoria` varchar(50) COLLATE utf8mb4_polish_ci NOT NULL,
  `adresat` varchar(50) COLLATE utf8mb4_polish_ci NOT NULL,
  `zdjecie` varchar(50) COLLATE utf8mb4_polish_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_polish_ci;

--
-- Dumping data for table `emaile`
--

INSERT INTO `emaile` (`id`, `nadawca`, `tytul`, `tresc`, `kategoria`, `adresat`, `zdjecie`) VALUES
(1, 'ttt', 'tttttttt', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', 'Odebrane', 'ty@zmail.com', ''),
(2, 'nadawca', 'odebrana', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', 'Odebrane', 'ty@zmail.com', ''),
(3, 'nadawca', 'Spam', 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32.\r\n\r\nThe standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from \"de Finibus Bonorum et Malorum\" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32.\r\n\r\nThe standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from \"de Finibus Bonorum et Malorum\" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.', 'Odebrane', 'ty@zmail.com', ''),
(4, 'nadawca', 'wyslana', 'Lorem Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32.\r\n\r\nThe standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from \"de Finibus Bonorum et Malorum\" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.is sim', 'Odebrane', 'ty@zmail.com', ''),
(5, 'nadawca', 'robocze', 'Cras pulvinar lacus eu dui congue egestas. Cras quis tortor eu felis luctus iaculis a sed metus. Maecenas mattis quis lectus a egestas. Nam non elementum quam. Proin vel augue eu eros facilisis pellentesque vitae ac erat. Donec fermentum risus urna. Etiam ut blandit urna.\r\n\r\nUt leo libero, hendrerit sed porta ut, varius a ipsum. Ut dictum sollicitudin ipsum ac bibendum. Morbi interdum hendrerit hendrerit. Integer libero velit, elementum id purus sit amet, sollicitudin facilisis arcu. Duis hendrerit orci sit amet lacus pharetra tincidunt sed sit amet diam. Quisque bibendum ipsum in est mollis, sit amet condimentum sem venenatis. Sed aliquet purus quis ex tincidunt dapibus. Sed malesuada ex eu purus porta sollicitudin eget a sem. Suspendisse et nisi eu risus imperdiet cursus at vitae nisl. Proin consequat pretium justo et sollicitudin. Donec a sapien arcu.', 'Odebrane', 'ty@zmail.com', ''),
(6, 'ty@zmail.com', 'wyslana2', 'Donec ullamcorper, massa non consequat consequat, ipsum elit scelerisque felis, eu bibendum neque dolor eu sem. Phasellus mi tellus, pretium id est eget, luctus semper ligula. Pellentesque vitae scelerisque turpis. Nullam aliquet scelerisque turpis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam rhoncus vestibulum lacus vulputate condimentum. Vestibulum in mauris bibendum, tincidunt eros et, faucibus mi. Suspendisse potenti. Vestibulum tincidunt nunc erat. Aliquam malesuada, ipsum in ultrices laoreet, arcu nulla tincidunt eros, vehicula convallis nisl justo sed libero.', 'Wyslane', 'adresat', ''),
(7, 'ty@zmail.com', 'WYSLANA', 'Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi convallis vestibulum magna, eu pulvinar est semper in. Phasellus rhoncus felis eu enim tincidunt commodo. Aenean eget mollis tortor. Sed interdum eros ut leo euismod faucibus. Integer eleifend, mauris sit amet faucibus tempor, nulla est tristique mi, nec egestas justo arcu non est. Vivamus et ligula elit. Morbi odio felis, molestie nec diam ac, blandit tincidunt sapien. Proin at volutpat metus, quis posuere orci. Sed sit amet nulla blandit, vulputate tortor at, egestas nulla.', 'Wyslane', 'adresat', ''),
(8, 'ty@zmail.com', 'tytul', 'Donec ullamcorper, massa non consequat consequat, ipsum elit scelerisque felis, eu bibendum neque dolor eu sem. Phasellus mi tellus, pretium id est eget, luctus semper ligula. Pellentesque vitae scelerisque turpis. Nullam aliquet scelerisque turpis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam rhoncus vestibulum lacus vulputate condimentum. Vestibulum in mauris bibendum, tincidunt eros et, faucibus mi. Suspendisse potenti. Vestibulum tincidunt nunc erat. Aliquam malesuada, ipsum in ultrices laoreet, arcu nulla tincidunt eros, vehicula convallis nisl justo sed libero.', 'Spam', 'adresat', ''),
(9, 'TY@zmail.com', 'tytul', 'Cras pulvinar lacus eu dui congue egestas. Cras quis tortor eu felis luctus iaculis a sed metus. Maecenas mattis quis lectus a egestas. Nam non elementum quam. Proin vel augue eu eros facilisis pellentesque vitae ac erat. Donec fermentum risus urna. Etiam ut blandit urna.\r\n\r\nUt leo libero, hendrerit sed porta ut, varius a ipsum. Ut dictum sollicitudin ipsum ac bibendum. Morbi interdum hendrerit hendrerit. Integer libero velit, elementum id purus sit amet, sollicitudin facilisis arcu. Duis hendrerit orci sit amet lacus pharetra tincidunt sed sit amet diam. Quisque bibendum ipsum in est mollis, sit amet condimentum sem venenatis. Sed aliquet purus quis ex tincidunt dapibus. Sed malesuada ex eu purus porta sollicitudin eget a sem. Suspendisse et nisi eu risus imperdiet cursus at vitae nisl. Proin consequat pretium justo et sollicitudin. Donec a sapien arcu.', 'Spam', 'adresat', ''),
(10, 'TY@zmail.com', 'ddddddddddddddd', 'Donec ullamcorper, massa non consequat consequat, ipsum elit scelerisque felis, eu bibendum neque dolor eu sem. Phasellus mi tellus, pretium id est eget, luctus semper ligula. Pellentesque vitae scelerisque turpis. Nullam aliquet scelerisque turpis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam rhoncus vestibulum lacus vulputate condimentum. Vestibulum in mauris bibendum, tincidunt eros et, faucibus mi. Suspendisse potenti. Vestibulum tincidunt nunc erat. Aliquam malesuada, ipsum in ultrices laoreet, arcu nulla tincidunt eros, vehicula convallis nisl justo sed libero.', 'spam', 'adresarrr', ''),
(11, 'TY@zmail.com', 'asd', 'Maecenas suscipit rhoncus posuere. Vivamus eget dui diam. Pellentesque ipsum mi, lacinia at fermentum quis, congue sit amet mauris. Suspendisse ultricies odio sit amet porta venenatis. Aenean ante ex, hendrerit non finibus ac, malesuada eget turpis. Sed et finibus diam, ut bibendum purus. Morbi in magna vitae nulla placerat posuere. Suspendisse in mattis lectus, eu ultricies ipsum. Proin tellus leo, cursus ut rhoncus et, suscipit non ex. Sed ut tempor sapien, eget maximus sem. Curabitur blandit eget sapien eu hendrerit. Ut tincidunt porttitor sollicitudin. Sed neque elit, bibendum ac odio in, accumsan facilisis nulla.', 'Wyslane', 'adresat', 'C:\\fakepath\\kotttt.png'),
(12, 'TY@zmail.com', 'tytul', 'Suspendisse potenti. Vestibulum in convallis quam, eu blandit lacus. Vestibulum aliquet cursus purus. Vestibulum blandit tortor est, eu blandit elit commodo non. Sed molestie, arcu non hendrerit pharetra, urna massa iaculis eros, sed vulputate sem odio imperdiet mauris. Vestibulum mattis dolor felis, sed blandit massa suscipit eu. Maecenas id tellus ac enim commodo pulvinar. Vestibulum non est in ligula venenatis ultrices non quis enim. Donec enim nulla, lacinia vitae nisl vel, sodales tristique magna.', 'Robocze', 'adresat', ''),
(13, 'TY@zmail.com', 'gvhng', 'Maecenas suscipit rhoncus posuere. Vivamus eget dui diam. Pellentesque ipsum mi, lacinia at fermentum quis, congue sit amet mauris. Suspendisse ultricies odio sit amet porta venenatis. Aenean ante ex, hendrerit non finibus ac, malesuada eget turpis. Sed et finibus diam, ut bibendum purus. Morbi in magna vitae nulla placerat posuere. Suspendisse in mattis lectus, eu ultricies ipsum. Proin tellus leo, cursus ut rhoncus et, suscipit non ex. Sed ut tempor sapien, eget maximus sem. Curabitur blandit eget sapien eu hendrerit. Ut tincidunt porttitor sollicitudin. Sed neque elit, bibendum ac odio in, accumsan facilisis nulla.', 'Robocze', 'adresat', ''),
(14, 'TY@zmail.com', 'sdfsadf', 'Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi convallis vestibulum magna, eu pulvinar est semper in. Phasellus rhoncus felis eu enim tincidunt commodo. Aenean eget mollis tortor. Sed interdum eros ut leo euismod faucibus. Integer eleifend, mauris sit amet faucibus tempor, nulla est tristique mi, nec egestas justo arcu non est. Vivamus et ligula elit. Morbi odio felis, molestie nec diam ac, blandit tincidunt sapien. Proin at volutpat metus, quis posuere orci. Sed sit amet nulla blandit, vulputate tortor at, egestas nulla.', 'Robocze', 'sdfs', 'C:\\fakepath\\kotttt.png'),
(15, 'TY@zmail.com', 'costam', 'Cras pulvinar lacus eu dui congue egestas. Cras quis tortor eu felis luctus iaculis a sed metus. Maecenas mattis quis lectus a egestas. Nam non elementum quam. Proin vel augue eu eros facilisis pellentesque vitae ac erat. Donec fermentum risus urna. Etiam ut blandit urna.\r\n\r\nUt leo libero, hendrerit sed porta ut, varius a ipsum. Ut dictum sollicitudin ipsum ac bibendum. Morbi interdum hendrerit hendrerit. Integer libero velit, elementum id purus sit amet, sollicitudin facilisis arcu. Duis hendrerit orci sit amet lacus pharetra tincidunt sed sit amet diam. Quisque bibendum ipsum in est mollis, sit amet condimentum sem venenatis. Sed aliquet purus quis ex tincidunt dapibus. Sed malesuada ex eu purus porta sollicitudin eget a sem. Suspendisse et nisi eu risus imperdiet cursus at vitae nisl. Proin consequat pretium justo et sollicitudin. Donec a sapien arcu.', 'Wyslane', 'adresat', ''),
(16, 'TY@zmail.com', 'fff', 'Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi convallis vestibulum magna, eu pulvinar est semper in. Phasellus rhoncus felis eu enim tincidunt commodo. Aenean eget mollis tortor. Sed interdum eros ut leo euismod faucibus. Integer eleifend, mauris sit amet faucibus tempor, nulla est tristique mi, nec egestas justo arcu non est. Vivamus et ligula elit. Morbi odio felis, molestie nec diam ac, blandit tincidunt sapien. Proin at volutpat metus, quis posuere orci. Sed sit amet nulla blandit, vulputate tortor at, egestas nulla.', 'Wyslane', 'adresat', ''),
(17, 'TY@zmail.com', 'tytul', 'Suspendisse potenti. Vestibulum in convallis quam, eu blandit lacus. Vestibulum aliquet cursus purus. Vestibulum blandit tortor est, eu blandit elit commodo non. Sed molestie, arcu non hendrerit pharetra, urna massa iaculis eros, sed vulputate sem odio imperdiet mauris. Vestibulum mattis dolor felis, sed blandit massa suscipit eu. Maecenas id tellus ac enim commodo pulvinar. Vestibulum non est in ligula venenatis ultrices non quis enim. Donec enim nulla, lacinia vitae nisl vel, sodales tristique magna.', 'Wyslane', 'adresat', ''),
(18, 'TY@zmail.com', 'sdfsf', 'Donec ullamcorper, massa non consequat consequat, ipsum elit scelerisque felis, eu bibendum neque dolor eu sem. Phasellus mi tellus, pretium id est eget, luctus semper ligula. Pellentesque vitae scelerisque turpis. Nullam aliquet scelerisque turpis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam rhoncus vestibulum lacus vulputate condimentum. Vestibulum in mauris bibendum, tincidunt eros et, faucibus mi. Suspendisse potenti. Vestibulum tincidunt nunc erat. Aliquam malesuada, ipsum in ultrices laoreet, arcu nulla tincidunt eros, vehicula convallis nisl justo sed libero.', 'Wyslane', 'sdfsdf', ''),
(19, 'TY@zmail.com', 'tytul', 'Aenean nec blandit magna. Nulla aliquam erat sit amet auctor pharetra. Praesent consectetur nibh quis erat rutrum, et sollicitudin nisi semper. Vivamus finibus risus sagittis congue sagittis. Donec ac dignissim nulla, et vehicula nisi. Donec tincidunt ligula dolor, eu sodales nulla dictum sed. Suspendisse ut luctus metus. Donec iaculis odio ac lectus fringilla eleifend. Maecenas laoreet venenatis nibh, sit amet sollicitudin ante aliquet a. Donec ac accumsan nunc. Integer gravida convallis nunc sit amet aliquam. Cras a facilisis justo. Vestibulum mattis luctus nisi sit amet blandit.', 'Wyslane', 'adresat', ''),
(20, 'TY@zmail.com', 'tytul', 'Aenean nec blandit magna. Nulla aliquam erat sit amet auctor pharetra. Praesent consectetur nibh quis erat rutrum, et sollicitudin nisi semper. Vivamus finibus risus sagittis congue sagittis. Donec ac dignissim nulla, et vehicula nisi. Donec tincidunt ligula dolor, eu sodales nulla dictum sed. Suspendisse ut luctus metus. Donec iaculis odio ac lectus fringilla eleifend. Maecenas laoreet venenatis nibh, sit amet sollicitudin ante aliquet a. Donec ac accumsan nunc. Integer gravida convallis nunc sit amet aliquam. Cras a facilisis justo. Vestibulum mattis luctus nisi sit amet blandit.', 'Wyslane', 'adresat', ''),
(21, 'TY@zmail.com', 'Tytul wiadomosci', 'Tresc', 'Wyslane', 'Adresat', ''),
(22, 'TY@zmail.com', 'Tytul wiadomosci', 'Tresc', 'Robocze', 'Adresat', ''),
(23, 'TY@zmail.com', '2', '2', 'Robocze', '2', ''),
(24, 'TY@zmail.com', 'Tytul wiadomosci', 'Tresc', 'Robocze', 'Adresat', ''),
(25, 'TY@zmail.com', 'Tytul wiadomosci', 'Tresc', 'Wyslane', 'Adresat', ''),
(26, 'TY@zmail.com', 'Tytul wiadomosci', 'Tresc', 'Wyslane', 'Adresat', ''),
(27, 'TY@zmail.com', 'Tytul wiadomosci', 'Tresc wiadomosci', 'Wyslane', 'Adresat', ''),
(28, 'TY@zmail.com', 'Tytul wiadomosci', 'Tresc', 'Wyslane', 'Adresat', '');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `emaile`
--
ALTER TABLE `emaile`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `emaile`
--
ALTER TABLE `emaile`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=29;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
